### PR TITLE
Regular CI test and badge

### PR DESCRIPTION
**Pull request by nilseling**
Just a small addition to regularly test the modules. Maybe not even needed...
But is there a reason to fix the `poetry` version?
Cheers,
Nils

### CODE REVIEW

**Comment by plankter** [comment]
I don't think scheduled testing is needed. It brings no benefits over test hooks on commits and because we are paying for GitHub Actions hours, it just waste of resources.

Poetry version should be definitely fixed: there are often multiple breaking changes even between minor releases, but unfortunately there is no better alternative yet. Or do you mean version pinning in poetry.lock file for other dependencies?

Best regards,
Anton

**Comment by nilseling** [comment]
Hey, first I meant version pinning of poetry in the workflow file. But now looking at the poetry.lock file, there seem to be a lot of version pinning happening that is not captured in the `conda_imctools.yml` in the `ImcSegmentationPipeline` repo. So are the unit tests here suitable to assume the modules of the `ImcSegmentationPipeline` also work as expected? Sorry for these comment, I'm just trying to understand the setup and I'm still quite new to unit testing in python and CP. And I guess `python v3.9` is not supported?

**Comment by votti** [comment]
@Version Pinning: The ImcPlugins are exclusively run via Cellprofiler and thus need to be tested with the dependency versions that are of the CellProfiler version used. Thus one needs to make sure to keep aligned with the versions used in the latest/recommended CP.

This is independent of the versions that may be used in other parts of the `ImcSegmentationPipeline` as CellProfiler is installed independently and not via the Conda environment.

**Comment by nilseling** [comment]
Alright, thanks for the clarification! Then I'm going to close this PR for now.

**Pull request closed without merging**
